# Generated by Django 5.2.14 on 2026-05-25 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='player_count',
            field=models.IntegerField(default=4),
        ),
    ]
