# Generated by Django 5.2.14 on 2026-05-25 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_gamesession_player_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='ask_player_names',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='player',
            name='score',
            field=models.FloatField(default=0.0),
        ),
    ]
