# Generated by Django 5.2.14 on 2026-05-26 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_gamesession_ask_player_names_alter_player_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='is_generating',
            field=models.BooleanField(default=False),
        ),
    ]
