# Generated by Django 5.2.14 on 2026-06-26 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_submission_is_generating'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='word_limit',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
