# Generated by Django 5.2.16 on 2026-07-11 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0005_gamesession_word_limit"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="token",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
    ]
