name: Deploy to Cloud Run

on:
  push:
    branches:
      - main
  workflow_dispatch: {}



env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  REGION: europe-west4
  SERVICE_NAME: prompt-battle

jobs:
  deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Authenticate with Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Log in to Google Artifact Registry
        uses: docker/login-action@v3
        with:
          registry: europe-west4-docker.pkg.dev
          username: _json_key
          password: ${{ secrets.GCP_SA_KEY }}

      - name: Build and Push Container to Google Artifact Registry
        run: |
          IMAGE_TAG="europe-west4-docker.pkg.dev/${{ env.PROJECT_ID }}/prompt-battle/app:${{ github.sha }}"
          docker build -t $IMAGE_TAG .
          docker push $IMAGE_TAG
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

      - name: Deploy to Google Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: ${{ env.SERVICE_NAME }}
          region: ${{ env.REGION }}
          image: ${{ env.IMAGE_TAG }}
          env_vars: |
            DJANGO_SETTINGS_MODULE=core.settings
            DJANGO_DEBUG=False
            CSRF_TRUSTED_ORIGINS=https://prompt-battle-erzsapt6ia-ez.a.run.app,https://prompt-battle-710763785950.europe-west4.run.app
            GS_BUCKET_NAME=${{ secrets.GS_BUCKET_NAME }}
            GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }}
            ADMIN_PASSWORD=${{ secrets.ADMIN_PASSWORD }}
            DJANGO_SECRET_KEY=${{ secrets.DJANGO_SECRET_KEY }}
            ALLOWED_HOSTS=${{ secrets.ALLOWED_HOSTS }}
            CORS_ALLOWED_ORIGINS=${{ secrets.CORS_ALLOWED_ORIGINS }}
            DB_HOST=${{ secrets.DB_HOST }}
            DB_NAME=${{ secrets.DB_NAME }}
            DB_USER=${{ secrets.DB_USER }}
            DB_PASSWORD=${{ secrets.DB_PASSWORD }}
            DB_PORT=${{ secrets.DB_PORT }}
          flags: |
            --allow-unauthenticated
            --session-affinity
            --timeout=3600
            --max-instances=1

